<?php

/**
 * Implementation of hook_menu().
 */
function oprop_webform_menu() {
  $items['admin/config/content/webform/oprop'] = array(
    'title' => 'Oprop webform', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oprop_webform_settings'), 
    'access arguments' => array('administer site'), 
    'type' => MENU_LOCAL_ACTION,
  );
  
  return $items;
}

function oprop_webform_settings($form, &$form_state) {
  $form['oprop_webform_nids'] = array(
    '#type' => 'textfield',
    '#title' => t('Node ids'),
    '#default_value' => variable_get('oprop_webform_nids', ''),
    '#description' => t('Insert webform node ids seprated by a comma.')
  );

  $form['oprop_webform_list_ids'] = array(
    '#type' => 'textfield',
    '#title' => t('List ids'),
    '#default_value' => variable_get('oprop_webform_list_ids', ''),
    '#description' => t('Insert oprop list ids seprated by a comma.')
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_form_BASE_FORM_ID_alter().
 */
function oprop_webform_form_webform_client_form_alter(&$form, &$form_state, $form_id) {
  $nids = explode(',', variable_get('oprop_webform_nids', ''));
  if (is_array($nids) && !empty($nids[0])) {
    foreach ($nids as $nid) {
      if ($form_id == 'webform_client_form_' . $nid) {
        $form['#validate'][] = 'oprop_webform_form_validate';
        $form['#submit'][] = 'oprop_webform_form_submit';
      }
    }
  }
}

function oprop_webform_form_validate($form, &$form_state) {
  //if ($form_state['values']['submitted']['oprop_webform_email'] != '') {
  //}
}

function oprop_webform_form_submit($form, &$form_state) {
  if (!empty($form_state['values']['submitted_tree']['oprop_webform_subscribe']) &&
      !empty($form_state['values']['submitted_tree']['oprop_webform_email'])) {
    $list_ids = explode(',', variable_get('oprop_webform_list_ids', ''));
    if (is_array($list_ids) && !empty($list_ids[0])) {
      $name = isset($form_state['values']['submitted_tree']['oprop_webform_name']) ? $form_state['values']['submitted_tree']['oprop_webform_name'] : '';
      $email = $form_state['values']['submitted_tree']['oprop_webform_email'];
      if ($result = oprop_api_list_subscribe($list_ids, $email, $name)) {
        drupal_set_message(t('You have been signed up for our newsletter'));
      }
      else {
        watchdog('oprop_webform', 'Error subscribing @mail, result: @result', array('@result' => print_r($result, TRUE), '@mail' => $email), WATCHDOG_ERROR);
      }
    }
  }
}