<?php
/**
 * Implementation of hook_menu()
 */
function opropimagefix_menu() {
	$items = array();

	// Submissions listing.
	$items['images/nyhedsbrev'] = array(
	  'title' => 'Image',
	  'page callback' => 'opropimagefix_show_file',
	  'access callback' => 'user_access',
	  'access arguments' => array('access content'),
	  'type' => MENU_CALLBACK,
	);

	return $items;
}

function opropimagefix_show_file() {
  $args = func_get_args();
  $file = dirname(__FILE__) . '/' . implode('/', $args);
  $path_parts = pathinfo($file);
  $extension = isset($path_parts['extension']) ? $path_parts['extension'] : NULL;
  $allowed_extensions = array('gif', 'jpeg', 'jpg', 'png');
  // Kollage is ok with files WITHOUT file extensions... 
  // Only relevant in the "img" folder.
  if ($args[0] == 'img' && !$extension) {
    foreach ($allowed_extensions as $extension) {
      if (file_exists($file . '.' . $extension)) {
        $file .= '.' . $extension;        
        break;
      }
    }
  }

  if (in_array($extension, $allowed_extensions)) {
    // Old files from Kollage have some special naming convention, when extracted from VIP.
    if ($args[0] == 'upload') {
      if (in_array($extension, array('gif', 'png'))) {
        $file = str_replace('.', '#', $file) . '.' . $extension;
      }
      elseif ($extension == 'jpg') {
        $file = str_replace('.', '#', $file) . '.' . 'jpeg';
      }
    }

    if (file_exists($file)) {
      header('Content-Type: image/' . $extension);
      header('Content-Length: ' . filesize($file));
      ob_clean();
      flush();
      readfile($file);
      exit;
    }
  }
}