<?php
/**
 * @file
 * This module intends to deal with the EU Directive on Privacy and Electronic
 * Communications that comes into effect in the UK on 26th May 2012.
 *
 */

/**
 * Implements hook_menu().
 */
function pco_cookie_menu() {
  $items['admin/config/system/pco-cookie'] = array(
    'title' => 'Peytz cookie',
    'description' => 'Make your website compliant with the EU Directive on Privacy and Electronic Communications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pco_cookie_admin_form'),
    'access arguments' => array('administer pco cookie popup'),
    'file' => 'pco_cookie.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function pco_cookie_init() {
  global $user;
  $popup_settings = pco_cookie_get_settings();

  if (user_access('display pco cookie popup') && $user->uid != 1) {
    global $language;

    drupal_add_css(drupal_get_path('module', 'pco_cookie') . '/css/pco_cookie.css');

    $popup_text_info = nl2br($popup_settings[$language->language . '_popup_info']);
    $html_info = theme('pco_cookie_popup_info', array('message' => $popup_text_info));
    $variables = array(
      'popup_html_info' => empty($html_info) ? FALSE : $html_info,
      'popup_height' => ($popup_settings['popup_height']) ? (int) $popup_settings['popup_height'] : 'auto',
      'popup_width' => (drupal_substr($popup_settings['popup_width'], -1) == '%') ? $popup_settings['popup_width'] : (int) $popup_settings['popup_width'],
      'popup_delay' => (int) ($popup_settings['popup_delay'] * 1000),
    );
    drupal_add_js(array('pco_cookie' => $variables), array('type' => 'setting', 'scope' => 'footer'));
    drupal_add_js(drupal_get_path('module', 'pco_cookie') . '/js/pco_cookie.js', array('type' => 'file', 'scope' => 'footer'));
  }
}

/**
 * Implements hook_permission().
 */
function pco_cookie_permission() {
  return array(
    'administer pco cookie popup' => array(
      'title' => 'Administer PCO Cookie popup'
    ),
    'display pco cookie popup' => array(
      'title' => 'Display PCO Cookie popup'
    ),
  );
}

/**
 * Implements hook_theme().
 */
function pco_cookie_theme() {
  $path = drupal_get_path('module', 'pco_cookie') . '/theme';
  return array(
    'pco_cookie_popup_info' => array(
      'template' => 'pco-cookie-popup-info',
      'variables' => array('message' => NULL),
      'path' => $path,
    )
  );
}

/**
 * Retrieves settings from the database.
 */

function pco_cookie_get_settings() {
  return variable_get('pco_cookie', array());
}
