
if(!window['_telemetric']) {

	(function(n,h){function B(){for(var a=!1,b=0;b<z.length;b++){try{a=z[b]()}catch(c){continue}break}return a}function A(a,b,c){var d=B();d&&(d.open(c?"POST":"GET",a,!0),c&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded"),d.onreadystatechange=function(){4==d.readyState&&(200!=d.status&&304!=d.status||b(d))},4!=d.readyState&&d.send(c))}function t(){n.addEventListener?(n.removeEventListener("DOMContentLoaded",t,!1),b.ready()):"complete"===n.readyState&&(n.detachEvent("onreadystatechange",
t),b.ready())}var y=[],s,b,p=h.encodeURIComponent,C=h.encodeURI;s=function(){this.j=[]};s.prototype={then:function(a,b,c){var d=new s,g={},q=this;g.resolve=function(b){var c;try{c=a&&a(b)}catch(f){d.reject(f)}c instanceof s?c.then(function(a){d.resolve(a)},function(a){d.reject(a)}):d.resolve(c)};g.reject=function(a){var c;if(b)try{c=b(a),d.resolve(c)}catch(g){d.reject(g)}else d.reject(a)};c&&(this.N=setTimeout(function(){q.reject(Error("Timed out after "+c+"ms"))},c));this.j.push(g);return d},resolve:function(a){this.q("resolve",
a)},reject:function(a){this.q("reject",a)},q:function(a,b){var c,d=0;this.N&&clearTimeout(this.N);this.then="resolve"===a?function(a){var c,d=new s;try{c=a&&a(b)}catch(m){d.reject(m)}c instanceof s?c.then(function(a){d.resolve(a)},function(a){d.reject(a)}):d.resolve(c);return d}:function(a,c){var d,m=new s;if(c)try{d=c&&c(b),m.resolve(d)}catch(l){m.reject(l)}else m.reject(b);return m};for(this.resolve=this.reject=function(){throw Error("Already complete");};c=this.j[d++];)c[a]&&c[a](b);delete this.j},
T:function(a){this.then(null,a)}};var z=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];b={S:2,Ba:{Ma:"phone-number",Ha:"phone-number"},h:{K:"__telemetric.s",O:"__telemetric.v"},R:2083,qa:30,ya:1051200,o:function(a,b,c){var d="";c&&(d=new Date,d.setTime(d.getTime()+6E4*c),d="; expires="+d.toGMTString());return n.cookie=a+"="+b+d+"; path=/"},
c:function(a){a+="=";var b,c,d=n.cookie.split(";");for(b=0;b<d.length;b+=1){for(c=d[b];" "===c.charAt(0);)c=c.substring(1,c.length);if(0===c.indexOf(a))return c.substring(a.length,c.length)}return null},V:function(a){try{a=decodeURI(a)}catch(b){if("URIError"===b.name)a=unescape(a);else throw b;}return C(a)},currentTime:function(){return+new Date},g:function(a){return Array.prototype.indexOf.apply(a,Array.prototype.slice.call(arguments,1))},f:null,l:"",$:function(a,f,c,d,g,q,k){var m=n.createElement("script"),
l;l=b.currentTime();var w=b.p,u=b.ua;m.type="text/javascript";f=b.V(f);l=[["z",l].join("="),["v",b.S].join("=")];null!==g&&l.push(["tmid",g].join("="));null!==q&&l.push(["gaid",q].join("="));l.push(["s",p(k.split(".")[1])].join("="));l.push(["n",p(a.join())].join("="));l.push(["r",p(f)].join("="));l.push(["l",p(c)].join("="));l.push(["t",p(d)].join("="));(a=h[w]&&h[w][u]||"")&&l.push(["pn",p(a)].join("="));a=("https:"===n.location.protocol?"https":"http")+"://"+b.f+b.l+"?"+l.join("&");a.length>b.R&&
A(("https:"===n.location.protocol?"https":"http")+"://"+b.f+b.l,function(a){200===a.status&&a.responseText&&Function(a.responseText)()},l);m.src=a;l=n.getElementsByTagName("script")[0];l.parentNode.insertBefore(m,l)},a:function(a,b){var c,d=a.length;if(void 0===d||"function"===typeof a)for(c in a){if(a.hasOwnProperty(c)&&!1===b.call(a[c],c,a[c]))break}else for(c=0;c<d&&!1!==b.call(a[c],c,a[c]);c+=1);return a},W:function(a,b){for(var c in b)a[c]=b[c];return a},Ia:!1,Ga:function(){return{start:function(){this.va=
(new Date).getTime()},stop:function(){this.wa=(new Date).getTime()},getTime:function(){return this.va-this.wa},Ja:function(){}}},s:!1,u:"https://track.adform.net/serving/cookie/?adfaction=getjs;adfcookname=uid",ra:function(a){b.u=a},X:function(a){var f=new s,c=n.createElement("script"),d=n.getElementsByTagName("body")[0],g=!1;a||(a=b.u);c.type="text/javascript";c.src=a;c.onload=c.onreadystatechange=function(){g||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(h.Adform&&
h.Adform._uid?(f.resolve(h.Adform._uid),g=!0):f.reject(Error("Error loading Adform UID")))};c.onerror=function(){f.reject(Error("Error loading Adform UID"))};d.appendChild(c);return f},F:!1,Z:function(){var a=new s,f,c,d,g;d=function(){var a=h.$netminers;return a&&a.uid&&a.sid?[a.uid,a.sid]:null};g=d();c=function(){if(g=d())try{a.resolve(g)}catch(q){"Already complete"===q.message?b.d(Error("Netminers Promise timed out")):b.d(q)}else f=setTimeout(c,250)};c();a.then(null,function(a){"Timed out"===e.message.substring(0,
9)&&clearTimeout(f);throw a;});return a},J:null,i:{P:250,Q:1250,C:null},v:null,w:function(){var a=b.c("svid")||"",f,c;if(!a){f="abcdef1234567890".split("");for(c=0;32>c;c++)a+=f[Math.round(Math.random()*(f.length-1))];b.o("svid",a,2628E3)||(a="")}return a},p:"s",L:"visitorID",ua:"pageName",sa:function(){var a=b.p,f=b.L,c,d;if(h[a])return h[a]&&!h[a][f]&&(h[a][f]=b.w()),h[a]&&h[a][f]||!1;c=function(){return h._s};d=function(a){h._s=a;a instanceof Object&&!a[f]&&(h._s[f]=b.w())};Object.defineProperty?
Object.defineProperty(h,a,{get:c,set:d,configurable:!0}):h.__defineGetter__&&(h.__defineGetter__(a,c),h.__defineSetter__(a,d));return!1},M:!1,aa:function(){var a=h._sz,f=/^ssl\.siteimprove.com\/event\.aspx\?/,c=new s;if(!b.M||!a||"function"!==typeof a.push)return c.resolve(null),c;a.push(["eventurl","1","1","1",function(a){var g=a;f.test(g)?g=g.replace(f,""):b.d({name:"SiteImproveError",message:"URL mismatch: "+a});c.resolve(g)}]);return c},k:!0,A:!1,B:"ga",ca:function(){var a=new s,f=b.B;if("function"===
typeof h[f])return h[f](function(b){var d=null;b||"function"!==typeof h[f].getAll||(b=(b=h[f].getAll())&&b[0]);b&&"function"===typeof b.get?d=b.get("clientId"):a.reject(Error("Tracker was null or did not have get() function"));a.resolve(d)}),a;a.resolve(null);return a},e:function(a){clearTimeout(b.J);b.J=setTimeout(function(){var a,c,d,g,q=b.i.C,k,m=b.p,l=b.L,w,u,x,v,r;b.k&&(a=b.c("__utma")||"",c=b.c("__utmb")||"",d=b.c("__utmz")||"");g=h[m]&&h[m][l]||"";x=b.c("s_vi");m=b.aa().then(function(a){u=
a},function(a){if("Timed out after 1500ms"!=a.message)throw a;b.d({name:"SITimeoutError",message:"SiteImprove timed out after 1500ms"})},1500);b.A&&(m=m.then(b.ca).then(function(a){w=a},function(a){if("Timed out after 1500ms"!=a.message)throw a;},1500));b.s&&(m=m.then(b.X).then(function(a){v=a},function(a){b.d(a)},3E3));b.F&&(m=m.then(b.Z).then(function(a){r=a},function(a){"Timed out after 1500ms"!=a.message&&b.d(a)},1500));m.then(function(){if(a||c||d||g||x||w||u||v||r)k=[],b.k&&(a&&k.push(["a",
p(a)].join("=")),c&&k.push(["b",p(c)].join("=")),d&&k.push(["z",p(d)].join("="))),g&&k.push(["s",p(g)].join("=")),x&&k.push(["v",p(x)].join("=")),w&&k.push(["u",p(w)].join("=")),u&&k.push(["si",p(u)].join("=")),r&&2===r.length&&(k.push(["nmu",p(r[0])].join("=")),k.push(["nms",p(r[1])].join("="))),v&&k.push(["adf",p(v)].join("=")),q.src=("https:"===n.location.protocol?"https":"http")+"://"+b.f+b.v+"?"+k.join("&")}).T(function(a){b.d(a)})},a)},t:!1,pa:function(a,f,c,d,g,q,k){var m,l,h=b.i.P,u=b.i.Q,
n=b.i.C=a.createElement("img");b.v=f;b.k=c;b.M=g;b.A=d;b.s=q;b.F=k;d=function(a){var d,f;d=(d=a&&a.split(";"))&&0<d.length&&d[0].split("=");f=m.apply(this,arguments);c&&d&&1<d.length&&/__utma|__utmb|__utmz/.test(d[0])&&b.e(h);return f};"function"!==typeof a.__lookupSetter__||"function"!==typeof a.__lookupSetter__("cookie")||b.t?"function"===typeof Object.getOwnPropertyDescriptor?(f=Object.getOwnPropertyDescriptor(a,"cookie"))&&"function"===typeof f.get?(m=f.set,f.set=d,Object.defineProperty(Object.getPrototypeOf(a),
"cookie",f),b.e(h)):b.e(u):b.e(u):(m=a.__lookupSetter__("cookie"),l=a.__lookupGetter__("cookie"),a.__defineGetter__("cookie",function(){return l.apply(a)}),a.__defineSetter__("cookie",d),b.t=!0,b.e(h));return n},ta:function(a,f){var c=b.h.O,d=b.c(c),g=[a,f].join("."),q=d&&parseInt(d.split(".")[0]);if(d&&q!==a)throw Error("Existing visitor ID "+d+" would be overwritten by "+g);b.o(c,g,b.ya)},ba:function(){var a=b.c(b.h.O);return a&&(a=a.split("."))&&2===a.length?[a[0],a[1]].join("."):null},Y:function(){var a=
b.c("__utma");return a&&(a=a.split("."))&&6===a.length?[a[1],a[2]].join("."):null},oa:function(a,f){var c,d,g={},q,k=2E3,k=1E4,m,l;if((d=a.getElementsByTagName("body"))&&0<d.length)d=d[0];else if(a.body)d=a.body;else throw Error("Unable to find document.body");l=function(a){return a?a.split("").join("[\u00a0 -]?"):a};b.a(f,function(a,b){if(b&&3!==b.length)throw Error("Invalid argument");var c=b[0],d=b[1],f=b[2],k=[b[0],b[2]].join(""),q;q=d?["(",l(d),"|\\([\u00a0 ]?",l(d),"[\u00a0 ]?\\))"].join(""):
l(d);g[k]={U:c,Ka:d,G:f,ia:new RegExp(["(\\+",l(c),"|",q,")[\u00a0 -]?"].join("")+l(f)),ka:new RegExp([q,l(f)].join("")),ja:new RegExp("\\+"+l(k)),n:[]}});q=function(a,c){b.a(c,function(){-1<a.nodeValue.search(this.ia)&&this.n.push(a)})};c=function(a){var c=b.currentTime(),d=0;(function r(a){for(var f=0;f<a.childNodes.length;f++){var l=a.childNodes[f];3==l.nodeType?q(l,g):r(l);d++;if(0===d%k&&b.currentTime()-c>k)throw m=Error(),m.name="TimeoutError",m.message="Iterative traversal timed out",m;}})(a)};
if("function"===typeof a.createTreeWalker&&"undefined"!==typeof h.NodeFilter)for(c=a.createTreeWalker(d,NodeFilter.SHOW_TEXT,null,!1),d=c.nextNode();d;)q(d,g),d=c.nextNode();else c(d);return b.H=g},H:{},ma:function(a,f){var c=b.H,d,g;b.a(f,function(f,k){c[f]&&(d=c[f].ka,g=c[f].ja,b.a(c[f].n,function(a,b){b.nodeValue=b.nodeValue.replace(g,k.formatted_intl);b.nodeValue=b.nodeValue.replace(d,k.formatted_national)}));b.la(a,c[f].G,k.number)})},la:function(a,f,c){var d,g,h=new RegExp("^(tel:.*)"+f.split("").join("[\u00a0 -]?")+
"$");b.a(a.getElementsByTagName("a"),function(a,b){try{d=b.getAttribute&&b.getAttribute("href")}catch(f){}d&&(g=d.match(h))&&b.setAttribute("href",g[1]+c)})},Ea:[],Ca:null,Fa:null,Da:[],I:function(){var a=h.Cufon,f=h._telemetric.cufon,c=f.cls;b.a(f.el,function(a,b){b.className=(b.className?b.className+" ":"")+c});a&&a.refresh&&a.refresh();a.replace=f.ore;f.ore=null;b.a(f.def,function(b,c){a.replace.apply(null,c)});f.def=[];f.cls=null},getElementsByClassName:function(a,b){return a.getElementsByClassName(b)},
na:function(a,f,c,d){var g,h,k,m,l,n="",p,s=-1<b.g(d,"*"),v;b.a(f,function(a,b){g=b.number;h=b.formatted_national;return!1});void 0!==g&&(v=function(a,b){return function(){this.onerror="";this.src=a;this.setAttribute("alt",b)}},a=b.getElementsByClassName(a,c),b.a(a,function(a,c){if(-1===b.g(d,c.tagName)&&!s)return!0;"IMG"===c.tagName?(k=c.src,p=c.getAttribute("alt"),c.onerror=v(k,p),m=k.lastIndexOf("."),l=k.lastIndexOf("?"),-1!==l&&(n=k.substring(l),k=k.substring(0,l)),c.src=-1!==m&&m>k.length-5?
k.substring(0,m)+"_"+g+k.substring(m)+n:k+"_"+g+n,c.setAttribute("alt",h)):c.innerHTML=h}))},m:null,d:function(a,f){var c=n.createElement("img"),d=[["n",p(a.name)].join("="),["m",p(a.message)].join("="),["s",a.stack?p(a.stack):""].join("=")];f||(f=("https:"==n.location.protocol?"https":"http")+"://"+b.f+b.m);c.src=f+"?"+d.join("&")},D:!1,ready:function(a){a?b.D?a():(y.push(a),"complete"===n.readyState?b.ready():n.addEventListener?(n.addEventListener("DOMContentLoaded",t,!1),h.addEventListener("load",
function(){b.ready()},!1)):(n.attachEvent("onreadystatechange",t),h.attachEvent("onload",function(){b.ready()}))):(b.D=!0,b.a(y,function(){try{this()}catch(a){b.d(a)}}),y=[])},xa:function(a){var b,c;c={};(b=a.match(/^([A-Za-z]+)?(:?\/\/)([0-9.\-A-Za-z]*)(?::(\d+))?(.*)$/))?(c.hostname=b[3].toLowerCase()||"",a=b[5]||""):c.hostname="";b=a.match(/([^?#]*)?(?:\?([^#]*))?(?:#(.*))?$/);c.path=b[1]||"";c.ga=b[2]||"";return c},ha:function(a,f,c){var d=!1;if(null===c)return!0;b.a(c,function(b,c){if(!(c[0]&&
!a.hostname.match(c[0])||c[1]&&!a.ga.match(c[1])||c[2]&&!f.search.match(c[2])))return d=!0,!1});return d},ea:function(a,b){return""===a.hostname||a.hostname===b.hostname},fa:function(a,f){var c=!0,d=f.pathname+f.search+f.hash;b.a(a,function(a,b){if(0===d.indexOf(b[0]))return c=b[1],!1});return c},da:function(a,f,c,d,g,q,k,m,l){var p=b.xa(q),s=!1,x=b.ba(n),v=b.Y(n),r,t,y=k.href;b.l=d;b.m=g;b.f=c;navigator.cookieEnabled&&(l&&l.uaGlobal&&(b.B=l.uaGlobal),m&&!b.fa(m,k)&&(s=!0),b.ready(function(){var c,
d=n.title,g=[];s||(c=b.oa(n,f),b.a(c,function(a,b){0<b.n.length&&g.push([b.U,b.G].join())}));r=b.c(b.h.K);b.ha(p,k,a)?(t=null!==r&&r.match(/^[01]\.[0-9]+/)?r.split(".")[1]:(new Date).getTime()/1E3|0,r="1."+t):b.ea(p,k)?null!==r&&r.match(/^[01]\.[0-9]+/)||(r="0."+((new Date).getTime()/1E3|0)):(t=null!==r&&r.match(/^[01]\.[0-9]+/)?r.split(".")[1]:(new Date).getTime()/1E3|0,r="0."+t);b.o(b.h.K,r,b.qa);r.match(/^1\./)?b.$(g,q,y,d,x,v,r):h._telemetric.cufon&&h._telemetric.cufon.cls&&b.I()}))},za:s,La:A};
n.getElementsByClassName||(b.getElementsByClassName=function(a,b){var c=[],d,g,h=new RegExp("(^| )"+b+"( |$)"),k=a.getElementsByTagName("*");d=0;for(g=k.length;d<g;d+=1)h.test(k[d].className)&&c.push(k[d]);return c});Array.prototype.indexOf||(b.g=function(a,b){if(null===a)throw new TypeError;var c=Object(a),d=c.length>>>0;if(0===d)return-1;var g=0;2<arguments.length&&(g=Number(arguments[2]),g!=g?g=0:0!=g&&Infinity!=g&&-Infinity!=g&&(g=(0<g||-1)*Math.floor(Math.abs(g))));if(g>=d)return-1;for(g=0<=
g?g:Math.max(d-Math.abs(g),0);g<d;g++)if(g in c&&c[g]===b)return g;return-1});h._telemetric||(h._telemetric={});b.W(h._telemetric,{b:b.I,init:b.da,ready:b.ready,r:b.ma,rc:b.na,readCookie:b.c,each:b.a,sc:b.pa,sv:b.ta,le:b.d,leu:b.m,adf:b.Aa,adfu:b.ra,ai:b.g,svid:b.sa,internals:b})})(document,window);


(function(document) {
    var source_whitelist = null,
	    nums = [["45", "", "72200199"]],
        referrer = document.referrer,
	    landingpage = document.location,
	    hostname  = 'web.telemetric.dk',
		path_limit = [],
	    get_number_url = '/t/422/n',
        error_url = '/t/elog/422',
        options = {},
	    _tm = window._telemetric;
	

    try {
        
        _tm.init(source_whitelist, nums, hostname, get_number_url, error_url, referrer, landingpage, path_limit, options);
    } catch (e) {
        _tm.le(e, ('https:' == document.location.protocol ? 'https' : 'http') + '://' + hostname + error_url);
    }

})(document);
}


